#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "No arguments supplied; please provide a parallelism count"
    exit 1
fi

tsc
mkdir data
node --inspect dist/server.js &
sleep 1
cargo run --release -- --count 100000 -m 30 -r 3 -q $1 -x 30
sleep 1



